import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/css/font.css";
import "@/styles/css/reset.css";
import "@/styles/css/style.css";
import "@/styles/css/globals.css";
import Providers from "@/lib/providers";
import { MenuResponse } from "@/types/main";
import API_URL from "@/api/endpoints";
import Header from "@/components/common/Header";
import { getNormal } from "@/api/fetchFilter";
import { getBaseUrl } from "@/lib/getBaseUrl";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const menusData = await getNormal<MenuResponse>(getBaseUrl() + API_URL.MAIN_MENU);
	const menuList = [...menusData.menuList].sort((a, b) => a.menuTopId - b.menuTopId);

	return (
		<html lang="ko">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<Providers>
					<Header menuList={menuList} />
					{children}
				</Providers>
			</body>
		</html>
	);
}
