import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import "@/styles/css/style.css";
import "@/styles/css/globals.css";
import { MenuResponse } from "@/types/main";
import API_URL from "@/api/endpoints";
import { getNormal } from "@/api/fetchFilter";
import { getApiUrl, getBackendUrl } from "@/lib/getBaseUrl";
import { getServerSession } from "@/lib/auth";
import { UserInfo } from "@/types/auth";
import { redirect } from "next/navigation";
import { cookies } from "next/he.aders";
import { ModalRoot } from "@/components/modal/core/ModalRoot";
import Providers from "@/app/Providers";
import { Header } from "@/app/Header";

const inter = Inter({
	subsets: ["latin"],
	variable: "--font-sans",
});

const robotoMono = Roboto_Mono({
	subsets: ["latin"],
	variable: "--font-mono",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	// 공통 메뉴 가져오기(SSR에서 가져올 떄는 직접 spring에서 가져오기)
	const menusData = await getNormal<MenuResponse>(getBackendUrl(API_URL.MAIN_MENU));
	console.log("menusData", menusData?.message);
	const menuList = [...menusData.menuList].sort((a, b) => a.menuTopId - b.menuTopId);

	return (
		<html lang="ko">
			<body className={`${inter.variable} ${robotoMono.variable} antialiased`}>
				<div className="wrap">
					<Providers>
						<Header menuList={menuList} />
						{children}
						<ModalRoot />
					</Providers>
				</div>
			</body>
		</html>
	);
}
